# Generated by Django 3.2.12 on 2022-04-19 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Data source name')),
                ('data_provider_id', models.CharField(max_length=255, verbose_name='Data provider')),
            ],
            options={
                'verbose_name': 'Data source',
                'verbose_name_plural': 'Data sources',
            },
        ),
        migrations.CreateModel(
            name='Mimetype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Mimetype')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Name')),
                ('size', models.PositiveIntegerField(default=0, help_text='Size in bytes', verbose_name='Size')),
                ('file_type', models.CharField(choices=[('directory', 'Directory'), ('file', 'File')], db_index=True, max_length=16, verbose_name='Node type')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated')),
                ('mimetype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='storage.mimetype', verbose_name='Mimetype')),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes',
            },
        ),
        migrations.CreateModel(
            name='DataSourceOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=512)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='storage.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='DataLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.datasource', verbose_name='Data source')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('root_dir', models.ForeignKey(limit_choices_to={'depth': 1}, on_delete=django.db.models.deletion.PROTECT, to='storage.node', verbose_name='Root directory')),
            ],
            options={
                'verbose_name': 'Data library',
                'verbose_name_plural': 'Data libraries',
            },
        ),
    ]
