# Generated by Django 3.2.16 on 2022-11-10 09:05

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordAttempt',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('attempt_date', models.DateTimeField(auto_now_add=True, verbose_name='Attempt date')),
                ('expire_date', models.DateTimeField(default=accounts.models._default_reset_expire_date, verbose_name='Expire date', db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
