# Generated by Django 3.2.13 on 2022-08-09 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import polyfile.storage.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, db_index=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Data library',
                'verbose_name_plural': 'Data libraries',
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, db_index=True)),
                ('name', models.CharField(max_length=255, verbose_name='Data source name')),
                ('data_provider_id', models.CharField(max_length=255, verbose_name='Data provider')),
                ('options', models.JSONField(default=dict, blank=True, null=False)),
            ],
            options={
                'verbose_name': 'Data source',
                'verbose_name_plural': 'Data sources',
            },
        ),
        migrations.CreateModel(
            name='Mimetype',
            fields=[
                ('name', models.CharField(max_length=256, verbose_name='Mimetype', primary_key=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Mime type',
                'verbose_name_plural': 'Mime types',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, db_index=True)),
                ('name', models.CharField(blank=False, db_index=True, max_length=255, verbose_name='Name')),
                ('file', polyfile.storage.fields.DynamicStorageFileField(upload_to='')),
                ('size', models.PositiveIntegerField(default=0, help_text='Size in bytes', verbose_name='Size')),
                ('file_type', models.CharField(choices=[('directory', 'Directory'), ('file', 'File')], db_index=True, max_length=16, verbose_name='Node type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date update')),
                ('data_library', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.datalibrary', verbose_name='Data library')),
                ('mimetype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='storage.mimetype', verbose_name='Mimetype')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children_set', to='storage.node')),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes',
            },
        ),
        migrations.CreateModel(
            name='AltNode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, db_index=True)),
                ('file', polyfile.storage.fields.DynamicStorageFileField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date update')),
                ('data_library', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.datalibrary', verbose_name='Data library')),
                ('mimetype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='storage.mimetype', verbose_name='Mimetype')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alt_nodes', to='storage.node')),
                ('version', models.CharField(db_index=True, max_length=255, verbose_name='Version')),
            ],
            options={'ordering': ['-id'], 'verbose_name': 'Alt Node', 'verbose_name_plural': 'Alt Nodes'},
        ),
        migrations.AddField(
            model_name='datalibrary',
            name='data_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.datasource', verbose_name='Data source'),
        ),
        migrations.AddField(
            model_name='datalibrary',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
