# Generated by Django 3.2.13 on 2022-08-09 21:37

from django.db import migrations
import polyfile.storage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='file',
            field=polyfile.storage.fields.DynamicStorageFileField(blank=True, upload_to=polyfile.storage.fields.DynamicStorageFileField.default_upload_to),
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('name', 'parent', 'data_library')},
        ),
        migrations.AlterUniqueTogether(
            name='altnode',
            unique_together={('node', 'version')},
        ),
    ]
